### ISSUE TITLE
dispatch scope on sever side

### ISSUE THREAD

**Issue by bobbyaxe61** [reduxjs/redux-thunk#295]
# Question
After much experimentation i have been able to set up redux on the sever side, my question now is how do i get the dispatch keyword to be global with redux-thunk eg in react i can do
   ```
 return (dispatch) => {
        dispatch({type: MASTER_APP_STATUS_PROCESSING});
    }
```
but now, i have redux set up on the server(nodejs) with redux-thunk applied as a middleware i have to do `store.dispatch({type: MASTER_APP_STATUS_PROCESSING});` not that there is anything wrong with this but will like to understand better. 

my current set setup has (react-redux, redux. redux-logger, redux-thunk). please i would like to know how to use redux-thunk on the server side thanks.

**Comment by timdorr** [comment]
The issue tracker here on GitHub is reserved for bug reports and feature requests. For usage questions (which is what I believe this is), please use Stack Overflow or Reactiflux where there are a lot more people ready to help you out. Thanks!

Please feel free to reply if you think this issue was closed prematurely.

**Comment by bobbyaxe61** [comment]
yes i completely understand but stack overflow hasn't been of much help on this particular issue i am all over the chat rooms and forums no help. is there possibly a small private channel where you can help me with this issue thank you.

**Comment by markerikson** [comment]
@bobbyaxe61 : As suggested, ask in the `#redux` channel in the Reactiflux Discord:

https://www.reactiflux.com
