### ISSUE TITLE
Middleware is not a function issue while unit testing my react redux thunk

### ISSUE THREAD

**Issue by anurag55555** [reduxjs/redux-thunk#297]
# Question
I was trying to test my thunk, as it has axios call so i am using moxios for mocking the axios call. For mocking the store and dispatching action i am using 'redux-mock-store'. But when i run the test error "middleware is not a function" generated, along with that it also says "unable to read property dispatch of undefined", that means my store is not getting mocked,i am unable to find the cause of this issue.

**the error is:**

![Screenshot from 2020-08-28 10-59-28](https://user-images.githubusercontent.com/60708486/91524785-b1879e80-e91d-11ea-9ee3-16b03d69be5e.png)

**Comment by timdorr** [comment]
The issue tracker here on GitHub is reserved for bug reports and feature requests. For usage questions (which is what I believe this is), please use Stack Overflow or Reactiflux where there are a lot more people ready to help you out. Thanks!

Please feel free to reply if you think this issue was closed prematurely.
