### ISSUE TITLE
No type hints when using dispatch

### ISSUE THREAD

**Issue by zqran** [reduxjs/redux-thunk#326]
# Bug Report

## Package name / version

redux-thunk@2.4.0

## Description

I found that when writing code in VSCode or Codesandbox, there is no clear type hint. 

The demo is as follows:
https://codesandbox.io/s/redux-thunk-ts-7ygmv?file=/src/index.ts

When you type the code, there will be no type hint for the `type` attribute
![image](https://user-images.githubusercontent.com/15389209/142126502-c8d00087-e2da-40f8-959d-c3e86d1553e2.png)

## Steps to reproduce

1. open the link
2. in the `testGetState` function, typing the code：`dispatch({ type })`
3. when you type the code, there will be no type hint for the `type` attribute

## Expected behavior

When typing the code ( `dispatch({ type })` ), there is a clear type hints

## Environment

- VSCode: [1.6.2]
- typescript: ["^4.4.4"]

**Comment by laat** [comment]
Is your problem that `type` cannot be inferred on the last line?
```
declare function unionArg(
  x: { type: 'FOO' } | { type: 'BAR'; x: number } | (() => void)
): void;

// type is any when hovering in vscode?
unionArg({type: })
```

I'm not sure this is an issue with redux-thunk. It's possibly a usability issue with typescript, because the types are correct.

**Comment by zqran** [comment]
@laat The **key point** is not that the type of `type` property is any, but when you typing the `type` attribute, there is no type hint.

> ```ts
> declare function unionArg(
>   x: { type: 'FOO' } | { type: 'BAR'; x: number } | (() => void)
> ): void;
> 
> // type is any when hovering in vscode?
> unionArg({type: })
> ```

However, the code you provided will prompt you when you typing the `type` attribute.

**Comment by laat** [comment]
I see, yes I can reproduce it.

**Comment by markerikson** [comment]
I spent some time today playing around with this. Loosely put, if I try rearranging the overloads, I _can_ get correct inference for `type` here, but some of our other typetests fail.

This is an edge case anyway. We generally expect that A) the thunk middleware will _not_ be typed to be restricted to a specific set of dispatchable actions (per https://redux.js.org/usage/usage-with-typescript#avoid-action-type-unions ), and B) users won't normally be hand-writing a `type` field in a plain action object as they dispatch because they'll be using action creators.

Given that, I don't think this is something we're going to fix, unless someone else comes up with a way to rearrange the types without breaking things.
