### ISSUE TITLE
during integrating thunk  into react-redux project, getting middleware is not a function error.

### ISSUE THREAD

**Issue by Arup-Upopadhyay** [reduxjs/redux-thunk#362]
# Bug Report
during integrating thunk  into react-redux project, getting middleware is not a function error.
Test URL:  https://codesandbox.io/p/sandbox/arup-react-redux-6rqx39

## Package name / version
 "redux": "5.0.0",
  "react-redux": "9.0.4",
  "redux-thunk": "3.1.0",

## Description
during integrating thunk  into react-redux project, getting middleware is not a function error
tried: https://stackoverflow.com/questions/44081111/why-am-i-getting-middleware-is-not-a-function-in-redux#:~:text=Your%20middleware%20--%20here%20thunkMiddleware%20--%20is%20not,already%20using%20ES6%20features%29%3A%20import%20thunkMiddleware%20from%20%27redux-thunk%27

tried: https://github.com/reduxjs/redux-thunk/issues/144

## Steps to reproduce
you can see it here: Test URL:  https://codesandbox.io/p/sandbox/arup-react-redux-6rqx39

## Expected behavior
It should work normally.

## Environment
Codesandbox

**Comment by markerikson** [comment]
The first issue is that the code in your example is using very outdated Redux patterns.

The _best_ answer here is to stop using the `redux` and `redux-thunk` packages by themselves, and instead use Redux Toolkit's `configureStore` method, which sets up both of those for you automatically:

- https://redux-toolkit.js.org/usage/migrating-to-modern-redux#store-setup-with-configurestore

That said, the issue here is that per the release notes and README, the Redux Thunk middleware is no longer a default export. _If_ you're going to use the older approach (which you shouldn't), you'd need `import { thunk } from "redux-thunk"`.
