### ISSUE TITLE
No default export for redux-thunk

### ISSUE THREAD

**Issue by Paviter-Singh** [reduxjs/redux-thunk#371]
# Bug Report

## Package name / version 
 "edux-thunk@3.1.0

redux-thunk@2.3.0

## Description
There is not default export for thunk

## Steps to reproduce
add default export

## Expected behavior
I belive there should be a default export for thunk

- Node/npm version: [e.g., Node 20.12.2/npm 10.5.0]

**Comment by EskiMojo14** [comment]
no, we intentionally switched to a named export in version 3. if any of our documentation still shows a default export, it is a mistake and a PR to fix it would be welcome. if you're following an external tutorial, it's likely out of date, as modern usage involves using `configureStore` instead of importing `thunk` yourself.

**Comment by chpio** [comment]
The readme still states that: https://www.npmjs.com/package/redux-thunk#manual-setup
(not on github tho)
